// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqTC8OhjM6--TKVOB1xZvnBB_9njBL0E',
    appId: '1:656565938424:web:e95b9cc999cd5ceabc730d',
    messagingSenderId: '656565938424',
    projectId: 'loan-a782e',
    authDomain: 'loan-a782e.firebaseapp.com',
    storageBucket: 'loan-a782e.firebasestorage.app',
    measurementId: 'G-WF6NY4CV3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQBRQgp_ihjlk4xGE9CODssABS4WqxZzQ',
    appId: '1:656565938424:android:9abc561ed0e4eb76bc730d',
    messagingSenderId: '656565938424',
    projectId: 'loan-a782e',
    storageBucket: 'loan-a782e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGy0fadv_dk_Z593R41jgeXUPV2BCx4qE',
    appId: '1:656565938424:ios:1b17d6fd14f554f9bc730d',
    messagingSenderId: '656565938424',
    projectId: 'loan-a782e',
    storageBucket: 'loan-a782e.firebasestorage.app',
    iosBundleId: 'com.phanhoang.moneynow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGy0fadv_dk_Z593R41jgeXUPV2BCx4qE',
    appId: '1:656565938424:ios:1b17d6fd14f554f9bc730d',
    messagingSenderId: '656565938424',
    projectId: 'loan-a782e',
    storageBucket: 'loan-a782e.firebasestorage.app',
    iosBundleId: 'com.example.loanAppFirebaseMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQqTC8OhjM6--TKVOB1xZvnBB_9njBL0E',
    appId: '1:656565938424:web:548d4b7fbf0ea3e5bc730d',
    messagingSenderId: '656565938424',
    projectId: 'loan-a782e',
    authDomain: 'loan-a782e.firebaseapp.com',
    storageBucket: 'loan-a782e.firebasestorage.app',
    measurementId: 'G-0KK8QWK25K',
  );

}
